apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: default
subsets:
  - addresses:
      - ip: 10.156.0.58 # your node's IP address
    ports:
      - port: 6379
        name: redis
        protocol: TCP